### PR TITLE
Integrate with MeBots

### LINKED ISSUE #1: Consider using MeBots to allow users to add this bot to GroupMe chats automatically
Hey there! I'm Erik, a developer of [another Python GroupMe bot](https://github.com/ErikBoesen/Yalebot). Motivated by frustration I experienced with building that bot, I recently developed [MeBots](http://mebots.co), which is a platform/API for building GroupMe bots more easily. It's designed to abstract away some of the headaches of maintaining GroupMe bots so that your job as a developer will be a little easier. For example, it has a whole built-in panel for adding and removing bots from different groups, and then it stores all the bot IDs and stuff in a database for you so you won't need to worry about keeping track of that data; you can just get what you need through a web API. Also, other people can add the bot to their own groups if you so choose. I think your bot could be of available to more people if it's on that marketplace and can be easily added by non-technical users.

I've written up some documentation for how to integrate with the API here: http://mebots.co/documentation. This would not be a complex change: each time a message was sent to a chat, there would just be one simple API request to check which bot_id to send with, and the website takes care of all the adding/removing logic for you!

I wrote some more specific documentation in the README of a pip package I made for easy integration with the API, which you can find [here](https://github.com/ErikBoesen/mebots.py), and there's a complete bot implementation [here](https://github.com/ErikBoesen/mebots-example-python)! I'm happy to make a PR integrating with the platform as well or answer any questions you may have about tradeoffs.

### PR DESCRIPTION
**Pull request by ErikBoesen**
Applying this change will require that you set an environment variable `BOT_TOKEN` on Heroku (see https://devcenter.heroku.com/articles/config-vars for help) to the token you get when creating your bot on MeBots (see http://mebots.co/documentation for an explanation of this process). I recommend you set a variable for the GroupMe token as well, and update the README accordingly. I am happy to give you advice on any aspect of this! :)

Fixes #1

### CODE REVIEW

**Comment by ErikBoesen** [comment]
Oh, also, you can change the name of the `BOT_TOKEN` environment variable if you want, and you can also change the `crosscountrybot` name I chose to something else. That was just an example which you're welcome to go with but don't have to.

**Comment by ErikBoesen** [comment]
@reteps hey, does this look OK?

**Comment by reteps** [comment]
Yeah, will look at it in a couple days.

**Comment by ErikBoesen** [comment]
No worries, I'm sure you're busy! :)

**Comment by reteps** [comment]
I decided that i would rather build directly off the api, so that any changes you make dont break my program. sorry!

**Pull request closed without merging**
